#!/bin/bash

set -e
set -x

check_sh_scripts() {
    find . -type f -name '*.sh' \
        -not -path './venv/*' \
        -exec "$@" {} +
    "$@" ./fix ./lint ./publish
}

ruff format --check --diff --quiet . ./bump-version
ruff check --diff . ./bump-version
ruff check . ./bump-version
mypy . ./bump-version
check_sh_scripts shellcheck
check_sh_scripts shfmt --diff --indent=4 --simplify
